apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: complex-k8s-ml-tls
spec:
  secretName: complex-k8s-ml
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: complex-k8s.ml
  dnsNames:
    - complex-k8s.ml
    - www.complex-k8s.ml
