apiVersion: networking.k8s.io/v1
# UPDATE API
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # ADD ANNOTATION
    nginx.ingress.kubernetes.io/use-regex: "true"
    # UPDATE ANNOTATION
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          # UPDATE PATH
          - path: /?(.*)
            # ADD PATHTYPE
            pathType: Prefix
            backend:
              # UPDATE SERVICE FIELDS
              service:
                name: client-cluster-ip-service
                port:
                  number: 3000
            # UPDATE PATH
          - path: /api/?(.*)
            # ADD PATHTYPE
            pathType: Prefix
            backend:
              # UPDATE SERVICE FIELDS
              service:
                name: server-cluster-ip-service
                port:
                  number: 5000
