name: Deployment process

on:
  push:
    branches:
      - master

jobs:
  before_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt GPG file
        env:
          SUPER_SECRET: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output ./service-account.json account-service.json.gpg
  build:
    runs-on: ubuntu-latest
    needs: before_install
    steps:
      - name: Read decrypted file
        run: cat service-account.json
